Dev
mur78/PY110-exam pull request #1
Opened 2021-12-14 15:11 UTC by mur78

Зачетное задание по курсу PythonPY110
Мамин Мурат Арифович

2021-12-29 10:20 UTC, aeksei requested changes
Работа выполнена хорошо! Добейте замечания по list comprehension
---

Если стоит статус **Changes requested**, то нужно в данную ветку внести обязательные изменения, которые представлены ниже. Если выше представлены комментарии, то они носят рекомендательный характер.
После нужно сделать "push", тогда коммиты с изменениями сразу попадут в "pull request". 
После этого можно самостоятельно сливать ветку и закрывать pull request

2021-12-29 10:20 UTC, aeksei commented on Main.py
> +Model_conf = "conf.py"
Если хотели описать, что эти переменные константы, то их нужно было записать полностью заглавными буквами

2021-12-29 10:20 UTC, aeksei commented on Main.py
> +    """Главная функция"""
Документация это всегда первая строка, не нужно оставлять здесь пустую строку

2021-12-29 10:20 UTC, aeksei commented on Main.py
> +        result.append(fake.name())
заменить на list comprehension

2022-01-03 19:50 UTC, mur78 commented
close pull request

2022-01-03 19:50 UTC, closed without merging